%%
%% src/leo_nfs_mount3.hrl was generated by erpcgen (do not edit)
%% date: Aug 9 22:05:26 2014
%%
-define(MOUNTPROG, 100005).
-define(MOUNTVERS3, 3).
-define(FHSIZE3, 64).
-define(FHSIZE, 32).
-define(MNTNAMLEN, 255).
-define(MNTPATHLEN, 1024).
